language: python
python:
  - "3.7"

cache:
  directories:
    - $HOME/.pip-cache/

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls flake8 responses requests-mock pytest-cov
# command to run tests
script:
  - flake8 eero
  - pytest --cov=eero --cov-report=term 

after_success:
  - coveralls

